name: Build Windows EXE
on: [push]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          pip install pygame numpy pyinstaller
          
      - name: Build EXE file
        run: |
          pyinstaller --onefile --windowed --add-data "*.png;." --name "4D_Visualizer" main.py
          
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: 4D_Visualizer-Windows
          path: dist/4D_Visualizer.exe
